services:
  mongo:
    image: mongo
    container_name: student-tracker-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty


  mongo-express:
    image: mongo-express
    container_name: student-tracker-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017/
  
  app:
    build: .
    container_name: student-app
    ports:
      - "5050:5050"
    depends_on:
      - mongo
    volumes:
      - .:/student-tracker
      - /student-tracker/node_modules

volumes:
  mongo-data:
